version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181




services:

  userservice:
    container_name: userserver
    image: quynhpv/userserver:s3
    ports:
      - 8080:8080
    depends_on:
      - hustappdb
      - eurekaserver
      - redis
    environment:
      KEYCLOAK_CREDENTIALS_SECRET: QlUWO8Zr0AqmbdXOqUIxPT0aj9L5t2Gx
      KEYCLOAK_REALM: master
      KEYCLOAK_AUTH_SERVER_URL:  http://172.17.0.1:7080
      KEYCLOAK_SSL_REQUIRED: none
      KEYCLOAK_RESOURCE: Hust-App
      KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS: true
      KEYCLOAK_BEARER_ONLY: true
      KEYCLOAK_CORS: true
      KEYCLOAK_PRINCIPAL_ATTRIBUTE: admin
      KEYCLOAK_USERNAME: admin
      KEYCLOAK_PASSWORD: admin

      SPRING_DATASOURCE_URL: jdbc:mysql://hustappdb:3306/hustappuser?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      EUREKA_INSTANCE_PREFERIPADDRESS: true
      EUREKA_CLIENT_REGISTERWITHEUREKA: true
      EUREKA_CLIENT_FETCHREGISTRY: true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - hustapp

  hustappdb:
    container_name: hustappdb
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: hustappuser
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./hustdata:/var/lib/mysql
    networks:
      - hustapp

  eurekaserver:
    container_name: eurekaserver
    image: tuyenhaitan/eurekaserver:s1
    ports:
      - 8070:8070
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    networks:
      - hustapp


  redis:
    container_name: redis-app
    image: redis
    ports:
      - 6379:6379
    networks:
      - hustapp

  minio:
    container_name: minio-app
    image: quay.io/minio/minio
    ports:
      - 9001:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=Tuyen18072001
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9090"
    networks:
      - hustapp

  datacollectionservice:
    container_name: datacollectionserver
    image: quynhpv/datacollectionserver:s3
    ports:
      - 8090:8090
    depends_on:
      - minio
      - hustappdb
      - eurekaserver
    environment:
      MINIO_BUCKET_NAME: hust-app
      MINIO_DEFAULT_FOLDER: /
      MINIO_ACCESS_NAME: root
      MINIO_ACCESS_SECRET: Tuyen18072001
      MINIO_URL: http://172.17.0.1:9001

      SERVICE_HOST: http://172.17.0.1:9001
      SERVER_IP: https://wetalk.ibme.edu.vn/upload

      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 100MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 100MB

      SPRING_DATASOURCE_URL: jdbc:mysql://hustappdb:3306/hustappuser?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      EUREKA_INSTANCE_PREFERIPADDRESS: true
      EUREKA_CLIENT_REGISTERWITHEUREKA: true
      EUREKA_CLIENT_FETCHREGISTRY: true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - hustapp


  hustlearningservice:
    container_name: hustlearningserver
    image: tuyenhaitan/hustlearningserver:s28
    ports:
      - 8060:8060
    depends_on:
      - hustappdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hustappdb:3306/hustappuser?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - hustapp


  chatservice:
    container_name: chatserver
    image: quynhpv/chatserver:s1
    ports:
      - 8050:8050
      - 8055:8055 # Socket IO Port
    depends_on:
      - hustappdb
      - eurekaserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hustappdb:3306/hustappuser?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      EUREKA_INSTANCE_PREFERIPADDRESS: true
      EUREKA_CLIENT_REGISTERWITHEUREKA: true
      EUREKA_CLIENT_FETCHREGISTRY: true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - hustapp

networks:
  hustapp:
    driver: "bridge"


