# Server port
server:
  port: 8060
#  ip: localhost:9090
  ip: 202.191.56.11/up

service:
  host: localhost:9001

spring:
  application:
    name: learningserver
  datasource:
    url: jdbc:mysql://202.191.56.11:3307/hustappuser
    username: root
    password: Hust20232
#    url: jdbc:mysql://202.191.56.11:3306/hustappuser
#    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  .servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 10000MB
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://202.191.56.11:8070/eureka/

#Email Config
mailServer:
  host: smtp.gmail.com
  port: 587
  email: phamquynhltbn12@gmail.com
  password: vbwpvroafrnttgvm
  protocol: smtp
  isSSL: false
  
# Minio
minio:
  access:
#    name: ROOTUSER
#    secret: CHANGEME123
      name: root
      secret: Tuyen18072001
  url: http://localhost:9001
  data_collection-bucket: data-collection
  vocabulary-bucket: vocabulary
  topic-bucket: topic
  question-bucket: question
  media_general-bucket: media_general

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
